#!/usr/bin/env bash
# Transfers a file from client to a server.
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ $# -lt 3 ]
then
 echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 kill -INT $$
fi

#scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
scp $1 $3@$2:$4
