#!/usr/bin/env bash
# Transfers a file from client to a server.
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ $# -lt 4 ]
then
 echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 kill -INT $$
fi

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
