#!/usr/bin/env bash
# Installs a webserver, nginx.
#   Install nginx on my server
#+  Nginx should listen on port 80
#+  When querying Nginx at it's root using curl, it must
#++ return a page containing the string Hello World!

sudo apt update
sudo apt install -y nginx

# Allow trafic on port 80
sudo ufw 'Nginx HTTP'

sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www/html
rm index.nginx-debian.html
echo "Hello World!" >> /var/www/html/index.html

service nginx restart
