#!/usr/bin/env bash
# Configures an Nginx sever to listen on port 80. Stops Nginx service.
#ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
#service nginx stop
