#!/usr/bin/env bash
# This script creates a file containing it's PID. It displays
#+ 'To infinity and beyond' indefinitely,
#+ 'I hate the kill command' when receiving a SIGTERM signal,
#+ and 'Y U no love me?!' when receiving a SIGINT signal.
#+ It deletes the file and terminates itself when receiving a
#+ SIGQUIT or SIGTERM signal

terminator() {
	rm /var/run/myscript.pid
	exit
}

echo $$ >> /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done
