#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but includes "Hi" on the 9th iteration.

i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	i=$(( i+=1 ))
done
