#!/usr/bin/env bash
# Configure ufw so that it redirects port 8080/TCP to port 80/TCP.

sudo apt install ufw
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw allow 8080/tcp

printf %s "*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
COMMIT" > /etc/ufw/before.rules

sudo ufw enable
