#!/usr/bin/env  bash
# Configures nginx to listen on all active IPs on port 8080
# Runs nginx as 'nginx' user

sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -c nginx service nginx restart
