#!/usr/bin/env  bash
# Configures nginx to listen on all active IPs on port 8080
# Runs nginx as 'nginx' user

sudo apt update
sudo apt install -y nginx

sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf

printf %s "server {
	listen 8080;
}" > /etc/nginx/sites-available/default

service nginx restart
