#!/usr/bin/env bash
# Configures nginx to listen on port 8080, Runs Nginx as 'nginx' user.
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill -9 apache
su nginx -c "service nginx restart"
