#!/usr/bin/env bash
# Configures nginx to listen on port 8080, Runs Nginx as 'nginx' user.
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
